from environs import Env

env = Env()
env.read_env()

APP_API_HOST = env('APP_API_HOST')
APP_API_PORT = env.int('APP_API_PORT')

POWER_SUPPLY_HOST = env('POWER_SUPPLY_HOST')
POWER_SUPPLY_PORT = env.int('POWER_SUPPLY_PORT')

POWER_SUPPLY_CH_COUNT = env.int('POWER_SUPPLY_CH_COUNT', 4)
TELEMETRY_REQ_SEC_PERIOD = env.int('TELEMETRY_REQ_SEC_PERIOD', 10)

TELEMETRY_LOG_FILE_PATH = env.path('TELEMETRY_LOG_FILE_PATH', 'telemetry_log.txt')
